#
# SPDX-FileCopyrightText: The LineageOS Project
# SPDX-License-Identifier: Apache-2.0
#

[versions]
agp = "8.13.0"
kotlin = "2.1.10"
activity = "1.7.2"
appcompat = "1.6.1"
coil = "2.6.0"
core = "1.12.0"
leanback = "1.2.0-alpha04"
lifecycle = "2.7.0"
material = "1.9.0"
palette = "1.0.0"
preference = "1.2.1"
tvprovider = "1.0.0"
generateBp = "+"

[libraries]
androidx-activity-ktx = { group = "androidx.activity", name = "activity-ktx", version.ref = "activity" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core" }
androidx-leanback = { group = "androidx.leanback", name = "leanback", version.ref = "leanback" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle" }
androidx-palette = { group = "androidx.palette", name = "palette", version.ref = "palette" }
androidx-preference = { group = "androidx.preference", name = "preference", version.ref = "preference" }
androidx-tvprovider = { group = "androidx.tvprovider", name = "tvprovider", version.ref = "tvprovider" }
coil = { group = "io.coil-kt", name = "coil", version.ref = "coil" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
lineageos-generatebp = { id = "org.lineageos.generatebp", version.ref = "generateBp" }
